language: rust
cache: cargo
rust:
  - nightly
script:
  # - cargo test --verbose
  - cargo build --release
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- windows
# - linux
# - osx
before_deploy:
  - cp $TRAVIS_BUILD_DIR/target/release/bibrust.exe $TRAVIS_BUILD_DIR/bundle
  - cd $TRAVIS_BUILD_DIR
  - tar -cf release.tar bundle
deploy:
  # edge: true # opt in to dpl v2
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB
  file_glob: true
  file: release.zip
  overwrite: true
  # draft: true
  on:
    tags: false