language: rust
cache: cargo
rust:
  - nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- windows
# - linux
# - osx
deploy:
  # edge: true # opt in to dpl v2
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB
  file_glob: true
  file: "*bibrust*"
  overwrite: true
  # draft: true
  on:
    tags: true