language: rust
rust:
  - nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- windows
- linux
- osx
deploy:
  api_key:
    secure: "14c1b5a76b06a2a72a84cfe8084b7d7ac7ed2689"   
  provider: releases
  token: <encrypted token>
  file: target/release/bibrust
  edge: true # opt in to dpl v2
  overwrite: true
  draft: true
  # on:
  #   tags: true