language: rust
rust:
  - nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- windows
# - linux
# - osx
deploy:
  edge: true # opt in to dpl v2
  skip_cleanup: true
  provider: releases
  api_key: GITHUB_TOKEN
  file: target/release/bibrust
  overwrite: true
  draft: true
  # on:
  #   tags: true