language: rust
cache: cargo
rust:
  - nightly
script:
  # - cargo test --verbose
  - cargo build --release
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- windows
- linux
- osx
before_deploy:
  # - export TRAVIS_TAG="latest"-$TRAVIS_OS_NAME
  - 'if [[ "$TRAVIS_OS_NAME" = "windows" ]]; then cp $TRAVIS_BUILD_DIR/target/release/bibrust.exe $TRAVIS_BUILD_DIR/bundle; fi'
  - 'if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then cp $TRAVIS_BUILD_DIR/target/release/bibrust $TRAVIS_BUILD_DIR/bundle; fi'
  - 'if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then cp $TRAVIS_BUILD_DIR/target/release/bibrust $TRAVIS_BUILD_DIR/bundle; fi'
  - cd $TRAVIS_BUILD_DIR
  - tar -cf $TRAVIS_OS_NAME.tar bundle
deploy:
  # edge: true # opt in to dpl v2
  skip_cleanup: true
  provider: releases
  api_key: $GITHUB
  file_glob: true
  file: $TRAVIS_BUILD_DIR/release.tar
  overwrite: true
  # draft: true
  on:
    tags: false
    all_branches: true