language: rust
rust:
  - nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
os:
- windows
- linux
- osx
deploy:
  skip_cleanup: true
  provider: releases
  token: 
    secure: $GITHUB_TOKEN
  file: target/release/bibrust
  edge: true # opt in to dpl v2
  overwrite: true
  draft: true
  # on:
  #   tags: true