name: Windows
on: [workflow_dispatch]

jobs:
  build:
    name: Rust project
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      # - name: Copy files to release folder
      #   working-directory: ./
      #   run: |
      #     pwd
      #     mkdir release -Force
      #     cp 00table.html release
      #     cp 01table.css release
      #     cp 02bundle.js release
      #     cp target/release/bibrust.exe release
      #     zip release.zip release –m –r

      - name: Release
        uses: softprops/action-gh-release@v1
        tag_name: release
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bibrust.exe
            00table.html
            01table.css
            02bundle.js 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
