name: Rust

on: [workflow_dispatch]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        toolchain: nightly
    - name: Build
      run: cargo build --verbose